### PR TITLE
Impl 992

### LINKED ISSUE #992: The hierarchy of map layer category doesn't work on map of profile page
This issue may related some codes on theme.
https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/issues/156

### PR DESCRIPTION
**Pull request by Huyeng**
Fixes #992 
- Enhance layer setting of map and profile
- Able to demonstrate the layers in hierarchy level of category on map thematic and profile.

### CODE REVIEW

File: inc/layers.php [hunk 1]
```diff
@@ -122,25 +123,29 @@ function post_layers_box($post = false) {
       <table class="layers-list available-layers">
        <tbody data-bind="foreach: filteredLayers">
         <tr>
-         <td><strong data-bind="text: title"></strong></td>
+         <td><strong><a data-bind="text: title, attr: {href: url}" target="_new"></a></strong></td>
```
Comment (acorbi) [inline inc/layers.php]: @Huyeng **target** attributes of <a> cannot have the value "_new" (https://www.w3schools.com/tags/att_a_target.asp). Did you maybe mean "_blank" here?

Comment (Huyeng) [inline inc/layers.php]: Well, either one is behave the same for the browsers. Anyways, we should use "_blank" instead.
