### PR TITLE
Fixes odm_excerpt() that chopped string in English and Khmer

### LINKED ISSUE #1026: The symbol charactor appears on Khmer site
image

### PR DESCRIPTION
**Pull request by Huyeng**
Fixes #1026

### CODE REVIEW

File: inc/utils/content.php [hunk 1]
```diff
@@ -444,37 +444,45 @@ function echo_post_meta($the_post, $show_elements = array('date','categories','t
...
+				if ($read_more != '') {
+					 $color_name = odm_country_manager()->get_current_country().'-color';
+					 $excerpt_words .=  " (<a href='".get_permalink($post->ID)." ' class='".$color_name."'>".__($read_more, 'odm').'</a>)';
+				}
+				return '<p>' . $excerpt_words . '</p>';
+			endif;
+		}
 
-		return '<p>' . $excerpt_words . '</p>';
+		return;
```
Comment (acorbi) [inline inc/utils/content.php]: @Huyeng nothing is retuned in this case? Maybe we should change it to return ```$translated_content``` in case ```$stripped_content``` is not set. (which I believe is not possible since strip_shortcodes always returns a string , see https://codex.wordpress.org/Function_Reference/strip_shortcodes )

Comment (Huyeng) [inline inc/utils/content.php]: if the $stripped_content has value, it will process the code in condition.

Comment (acorbi) [inline inc/utils/content.php]: and what happens if it does not have value? it returns nothing. Is it the behaviour you would expect?

Comment (Huyeng) [inline inc/utils/content.php]: Yes. Or we can end the process without return any if no value.  You are welcome to update it.
