### PR TITLE
Add is_admin condition to fix the filter posst issue on dashboad.

### LINKED ISSUE #732: Filter news posts by category on dashboar show result include the post of topic
In the News post type, if we would like to filter the posts by category, the result provides the topic posts instead. See the result url below:

https://opendevelopmentcambodia.net/wp-admin/edit.php?s&post_status=all&post_type=news-article&action=-1&m=0&cat=29647&filter_action=Filter&paged=1&action2=-1
screenshot at jan 28 17-45-07

### PR DESCRIPTION
**Pull request by Huyeng**
Fixes #732

### CODE REVIEW

File: functions.php [hunk 1]
```diff
@@ -404,36 +404,40 @@ function odm_custom_admin_css()
...
-  if(get_post_type()){
-    $post_type = $query->query['post_type'][0];
-  }else {
-    if (!is_admin() && ($query->is_search || get_query_var('odm_advanced_nav') || $query->is_tax || $query->is_category || $query->is_tag)) {
-      $query->set('post_type', available_post_types_search());
+  if(!is_admin()):
+    if(isset($query->query['post_type'])){
+      $query->set('post_type', $query->query['post_type']);
+    }else {
+      if (!is_admin() && ($query->is_search || get_query_var('odm_advanced_nav') || $query->is_tax || $query->is_category || $query->is_tag)) {
```
Comment (acorbi) [inline functions.php]: the ```!is_admin()``` part here is not needed, you are checking it on line 416

Comment (Huyeng) [inline functions.php]: You are right. I forgot to remove it after add it to the top. I will update it.
